### ISSUE TITLE
Application does not terminate by closing window

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#15] opened 2019-12-05 21:52 UTC
While the old version of WB succesfully terminates the application by closing the app's window, the new version of WB fails to do so, requiring user to use ctrl+c in the terminal corresponding to the app to fully terminate the application

**Comment by jConquest** [comment] 2020-07-15 02:45
This occurs when using the Simulation Starter

**Comment by jConquest** [comment] 2020-08-04 16:27
This may be related to the Analyze button issues. This will likely be addressed with the sim starter wizard.

**Comment by stevecl5** [comment] 2021-07-03 21:34
fixed in PR #84

**Comment by stevecl5** [comment] 2021-07-03 21:47
Adding info for future reference:

This appears to be caused by GUI threads (most likely from Java Swing components) that are not closed when the main display is closed. Resolved by calling `Platform.exit()` to close any JavaFX components and then `System.exit(0)` to ensure the JVM is terminated (i.e. close any remaining threads). If Java Swing components are removed in the future, this may become unnecessary.

**Closed** 2021-07-11 05:32 UTC
Labels: bug, good first issue
